version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:80"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - '8080:80'

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bestloan
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "9906:3306"